In [3]:
%%sql
use prod_db

Empty DataFrame
Columns: []
Index: []

Run SQL queries as shown below

In [4]:
%%sql
show tables

   namespace                  tableName  isTemporary
0    prod_db                     orders        False
1    prod_db               fct_lineitem        False
2    prod_db                   lineitem        False
3    prod_db                     nation        False
4    prod_db     order_lineitem_metrics        False
5    prod_db               dim_customer        False
6    prod_db                 stg_orders        False
7    prod_db               stg_customer        False
8    prod_db                 stg_nation        False
9    prod_db              wide_lineitem        False
10   prod_db                   partsupp        False
11   prod_db  customer_outreach_metrics        False
12   prod_db                   supplier        False
13   prod_db               stg_lineitem        False
14   prod_db                   customer        False
15   prod_db                       part        False
16   prod_db                 fct_orders        False
17   prod_db                     region        False
18   prod_db                 stg_region        False
19   prod_db                wide_orders        False

In [5]:
%%sql --show
select 1

   1
0  1

Run Python code as shown below

In [6]:
print(f'This is Python')

This is Python

In [3]:
%%sql
show catalogs;

         catalog
0          local
1  spark_catalog

In [5]:
%%sql
show schemas IN local;

  namespace
0      prod
1   prod_db

In [7]:
%%sql
show tables in prod_db;

   namespace                  tableName  isTemporary
0    prod_db                     orders        False
1    prod_db               fct_lineitem        False
2    prod_db                   lineitem        False
3    prod_db                     nation        False
4    prod_db     order_lineitem_metrics        False
5    prod_db               dim_customer        False
6    prod_db                 stg_orders        False
7    prod_db               stg_customer        False
8    prod_db                 stg_nation        False
9    prod_db              wide_lineitem        False
10   prod_db                   partsupp        False
11   prod_db  customer_outreach_metrics        False
12   prod_db                   supplier        False
13   prod_db               stg_lineitem        False
14   prod_db                   customer        False
15   prod_db                       part        False
16   prod_db                 fct_orders        False
17   prod_db                     region        False
18   prod_db                 stg_region        False
19   prod_db                wide_orders        False

In [10]:
%%sql
SELECT * from prod_db.customer Limit 10;

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,1,Customer#000000001,j5JsirBM9PsCy0O1m,15,25-989-741-2988,711.56,BUILDING,y final requests wake slyly quickly special ac...
1,2,Customer#000000002,487LW1dovn6Q4dMVymKwwLE9OKf3QG,13,23-768-687-3665,121.65,AUTOMOBILE,y carefully regular foxes. slyly regular reque...
2,3,Customer#000000003,fkRGN8nY4pkE,1,11-719-748-3364,7498.12,AUTOMOBILE,fully. carefully silent instructions sleep alo...
3,4,Customer#000000004,4u58h fqkyE,4,14-128-190-5944,2866.83,MACHINERY,sublate. fluffily even instructions are about th
4,5,Customer#000000005,hwBtxkoBF qSW4KrIk5U 2B1AU7H,3,13-750-942-6364,794.47,HOUSEHOLD,equests haggle furiously against the pending p...
5,6,Customer#000000006,"g1s,pzDenUEBW3O,2 pxu0f9n2g64rJrt5E",20,30-114-968-4951,7638.57,AUTOMOBILE,quickly silent asymptotes are slyly regular e...
6,7,Customer#000000007,8OkMVLQ1dK6Mbu6WG9 w4pLGQ n7MQ,18,28-190-982-9759,9561.95,AUTOMOBILE,"ounts. ironic, regular accounts sleep. final r..."
7,8,Customer#000000008,"j,pZ,Qp,qtFEo0r0c 92qobZtlhSuOqbE4JGV",17,27-147-574-9335,6819.74,BUILDING,riously final excuses sublate quickly among th...
8,9,Customer#000000009,vgIql8H6zoyuLMFNdAMLyE7 H9,8,18-338-906-3675,8324.07,FURNITURE,ss pinto beans believe slyly quiet deposits-- ...
9,10,Customer#000000010,"Vf mQ6Ug9Ucf5OKGYq fsaX AtfsO7,rwY",5,15-741-346-9870,2753.54,HOUSEHOLD,g quickly after the evenly bold

In [9]:
%%sql
-- all customer rows where the name has a 381 in it

SELECT  * 
FROM prod_db.customer as c
WHERE c.c_name LIKE "%381%"

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,381,Customer#000000381,wXs5zN2nPHqPsfFO,5,15-860-208-7093,9931.71,BUILDING,"ithely along the regular, regular theodolites...."
1,1381,Customer#000001381,kAgLl7nUiPStCleWOiKevH3QAOhqtg9dVvrdN,22,32-418-900-6494,367.82,BUILDING,posits sleep carefully around the slyly e
2,2381,Customer#000002381,"z7B43DZ7RGlkgEi3YaXfy,Aw2SZepYurvII41Do",5,15-493-990-8133,412.99,FURNITURE,ul requests use slyly quickly even deposits. s...
3,3381,Customer#000003381,03jULkpVTm92eKW24meIj,13,23-441-750-5088,2473.54,AUTOMOBILE,er the carefully bold multipliers doze blithel...
4,3810,Customer#000003810,hlRTIO4e4HNahc8A D,18,28-881-994-8196,9906.80,FURNITURE,bold requests after the furiousl
5,3811,Customer#000003811,b6vEJqifAgSbGhzTwTz,22,32-962-997-2221,5697.04,FURNITURE,he carefully special packages. regular deposit...
6,3812,Customer#000003812,HGYp5dZtlA,14,24-653-654-5032,4204.53,FURNITURE,y ironic requests believe blithely
7,3813,Customer#000003813,Aeky0En0JO5V1zRgFZ9EvCcBWaTmW,6,16-983-191-7833,-494.03,HOUSEHOLD,rding to the express foxes. bold platelets main
8,3814,Customer#000003814,FQ3lWCA3znooc3S SmDCfwqdn4R9,20,30-833-732-5401,-207.83,AUTOMOBILE,ounts alongside of the fluffily pendin
9,3815,Customer#000003815,S5SIUeDCuVOKRTZqZ5M4CC,19,29-968-870-7672,2887.99,FURNITURE,ccounts. fluffily bold requests sleep furio
10,3816,Customer#000003816,kFLu9DYSXH,6,16-806-750-3968,4353.05,AUTOMOBILE,g the carefully ironic asymptotes. furiously i...
11,3817,Customer#000003817,IWp4rgxgRxvUeHK2xtX8SEfGYmHYrCCpbBwXm,16,26-142-669-5787,9766.42,AUTOMOBILE,es until the bold instructions wake quickly ca...
12,3818,Customer#000003818,yrvC8HiUJVCsu7MyFHcyTcmAP0NgEWnoXQgTAz36,7,17-983-218-3716,346.99,AUTOMOBILE,theodolites. special instructions are blithel...
13,3819,Customer#000003819,TejxSl9G1aF1x,4,14-964-709-5782,-210.31,BUILDING,os. excuses boost quickly across the carefully...
14,4381,Customer#000004381,MIQXH5W6Zsup5cVYfCtWupiJtgi,2,12-570-797-1472,2542.55,HOUSEHOLD,r deposits. carefully even packages along
15,5381,Customer#000005381,"bXQ,KuigJB1nASXN73PDwNOvXCIkp5",5,15-700-184-7619,4130.88,MACHINERY,es. carefully ironic ideas sleep blithely abou...
16,6381,Customer#000006381,BKfk07DtN45gg2w4mMUK1,7,17-877-502-9214,7346.88,HOUSEHOLD,"inal asymptotes boost. bold, ironic requests a..."
17,7381,Customer#000007381,yq7RXRmclCUi6wJspelKaEWSJ TfycLah,20,30-666-139-1602,73.39,BUILDING,fluffily special requests are about the fluffi...
18,8381,Customer#000008381,7kbg8wegbgGmgiW8OQ4SbJ8colXl6rpBmHudJ,0,10-177-308-9094,6674.59,AUTOMOBILE,uests against the carefully bold excuses sleep...
19,9381,Customer#000009381,BhXODcEOpwNg6,17,27-708-588-6706,4788.15,HOUSEHOLD,sual hockey players use above the final packag...
20,10381,Customer#000010381,RLDSr5JOMK45,15,25-294-314-6077,106.15,FURNITURE,r the furiously unusual pinto beans. blithely ...
21,11381,Customer#000011381,cHcQKKDGnWLbq48O,7,17-652-294-7849,1959.81,MACHINERY,structions. slyly ironic requests play furiously
22,12381,Customer#000012381,hPUYchVeqkeLC1QCsGJXF5Fj6QDQhkd,13,23-989-969-2819,1172.56,HOUSEHOLD,"cies cajole carefully. unusual, ironic ideas b..."
23,13381,Customer#000013381,TkAwDfheF4H3g9H,9,19-465-107-1496,3221.83,HOUSEHOLD,efully regular foxes. ironic platelets sleep a...
24,13810,Customer#000013810,"KDptBRwrSNgIfqVU,Si2smGKFLFix",18,28-953-486-1222,5133.48,BUILDING,"lithely. slyly ironic pinto beans nag. ironic,..."
25,13811,Customer#000013811,XvajiqJbFBaY8IfkIPanJeDnrba,19,29-964-589-6640,3436.54,MACHINERY,ly regular theodolites: courts nag blithely. b...
26,13812,Customer#000013812,"WuM0MP,N22TPjuHnUzDbcyJF86fkycoa8L7xPsKK",0,10-571-845-2630,5982.87,AUTOMOBILE,lar ideas use carefully alongside of the fluff...
27,13813,Customer#000013813,Xh5saiXGJkv5 lL,21,31-140-142-6191,1190.11,MACHINERY,"te blithely even instructions. regular, final ..."
28,13814,Customer#000013814,PnsbC4EN7J4TZ30 yPPlI8xh,17,27-767-457-2550,2131.39,FURNITURE,"instructions according to the furious, ironic..."
29,13815,Customer#000013815,UHXyxzMMNwV dIRAGo,11,21-606-813-1389,4240.37,FURNITURE,special deposits. carefully daring requests sl...
30,13816,Customer#000013816,"XX Nlht,5lD6vroOC75qAS",17,27-501-367-6604,7844.29,AUTOMOBILE,ully final excuses. carefully unusual accounts...
31,13817,Customer#000013817,eg1g5BqcUMPqvGy9oY7bjVe7nj6NsH,3,13-978-449-6295,2094.32,FURNITURE,slyly. even theodolites nag regularly-- furiou...
32,13818,Customer#000013818,r17Nf8Y8iLfBKIGP6zJUrWl5K3g,15,25-948-173-6359,8239.56,HOUSEHOLD,cial courts. excuses sleep quickly regular acc...
33,13819,Customer#000013819,9MlFsiIsVNrVT8jJKRp30wISV5sNdXAwIT85F8S,12,22-868-584-6588,1312.29,BUILDING,ackages. carefully special pinto beans
34,14381,Customer#000014381,jakuN8Gt0SJNE,21,31-449-680-6297,1915.30,FURNITURE,the even accounts cajole blithely furiously e...

In [32]:
%%sql
select * from lineitem limit 10;

,l_orderkey,l_partkey,l_suppkey,l_linenumber,l_quantity,l_extendedprice,l_discount,l_tax,l_returnflag,l_linestatus,l_shipdate,l_commitdate,l_receiptdate,l_shipinstruct,l_shipmode,l_comment
0,1,15519,785,1,17.00,24386.67,0.04,0.02,N,O,1996-03-13,1996-02-12,1996-03-22,DELIVER IN PERSON,TRUCK,to beans x-ray carefull
1,1,6731,732,2,36.00,58958.28,0.09,0.06,N,O,1996-04-12,1996-02-28,1996-04-20,TAKE BACK RETURN,MAIL,according to the final foxes. qui
2,1,6370,371,3,8.00,10210.96,0.10,0.02,N,O,1996-01-29,1996-03-05,1996-01-31,TAKE BACK RETURN,REG AIR,ourts cajole above the furiou
3,1,214,465,4,28.00,31197.88,0.09,0.06,N,O,1996-04-21,1996-03-30,1996-05-16,NONE,AIR,s cajole busily above t
4,1,2403,160,5,24.00,31329.60,0.10,0.04,N,O,1996-03-30,1996-03-14,1996-04-01,NONE,FOB,"the regular, regular pa"
5,1,1564,67,6,32.00,46897.92,0.07,0.02,N,O,1996-01-30,1996-02-07,1996-02-03,DELIVER IN PERSON,MAIL,rouches. special
6,2,10617,138,1,38.00,58049.18,0.00,0.05,N,O,1997-01-28,1997-01-14,1997-02-02,TAKE BACK RETURN,RAIL,re. enticingly regular instruct
7,3,430,181,1,45.00,59869.35,0.06,0.00,R,F,1994-02-02,1994-01-04,1994-02-23,NONE,AIR,s cajole above the pinto beans. iro
8,3,1904,658,2,49.00,88489.10,0.10,0.00,R,F,1993-11-09,1993-12-20,1993-11-24,TAKE BACK RETURN,RAIL,ecial pinto beans. sly
9,3,12845,370,3,27.00,47461.68,0.06,0.07,A,F,1994-01-16,1993-11-22,1994-01-23,DELIVER IN PERSON,SHIP,e carefully fina

In [12]:
%%sql
DESCRIBE extended lineitem;

,col_name,data_type,comment
0,l_orderkey,bigint,NaN
1,l_partkey,bigint,NaN
2,l_suppkey,bigint,NaN
3,l_linenumber,int,NaN
4,l_quantity,"decimal(15,2)",NaN
5,l_extendedprice,"decimal(15,2)",NaN
6,l_discount,"decimal(15,2)",NaN
7,l_tax,"decimal(15,2)",NaN
8,l_returnflag,string,NaN
9,l_linestatus,string,NaN
10,l_shipdate,date,NaN
11,l_commitdate,date,NaN
12,l_receiptdate,date,NaN
13,l_shipinstruct,string,NaN
14,l_shipmode,string,NaN
15,l_comment,string,NaN
16,,,
17,# Metadata Columns,,
18,_spec_id,int,
19,_partition,struct<>,
20,_file,string,
21,_pos,bigint,
22,_deleted,boolean,
23,,,
24,# Detailed Table Information,,
25,Name,local.prod_db.lineitem,
26,Type,MANAGED,
27,Location,file:///home/airflow/warehouse/prod_db/lineitem,
28,Provider,iceberg,
29,Owner,root,
30,Table Properties,"[current-snapshot-id=5388258601340601859,forma...",
31,Statistics,"103298384 bytes, 600572 rows",NaN

In [15]:
%%sql
SET search_path = prod_db;
SELECT * FROM customer;

{"ts": "2026-09-01 20:48:21.276", "level": "ERROR", "logger": "SQLQueryContextLogger", "msg": "[INVALID_SET_SYNTAX] Expected format is 'SET', 'SET key', or 'SET key=value'. If you want to include special characters in key, or include semicolon in value, please use backquotes, e.g., SET `key`=`value`. SQLSTATE: 42000", "context": {"errorClass": "INVALID_SET_SYNTAX"}, "exception": {"class": "Py4JJavaError", "msg": "An error occurred while calling o38.sql.\n: org.apache.spark.sql.catalyst.parser.ParseException: \n[INVALID_SET_SYNTAX] Expected format is 'SET', 'SET key', or 'SET key=value'. If you want to include special characters in key, or include semicolon in value, please use backquotes, e.g., SET `key`=`value`. SQLSTATE: 42000\n== SQL (line 1, position 1) ==\nSET search_path = prod_db;\n^^^^^^^^^^^^^^^^^^^^^^^^^^\nSELECT * FROM customer;\n^^^^^^^^^^^^^^^^^^^^^^\n\n\tat org.apache.spark.sql.errors.QueryParsingErrors$.unexpectedFormatForSetConfigurationError(QueryParsingErrors.scala:531)\n\tat org.apache.spark.sql.execution.SparkSqlAstBuilder.$anonfun$visitSetConfiguration$1(SparkSqlParser.scala:118)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin(SparkParserUtils.scala:170)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin$(SparkParserUtils.scala:155)\n\tat org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:41)\n\tat org.apache.spark.sql.execution.SparkSqlAstBuilder.visitSetConfiguration(SparkSqlParser.scala:97)\n\tat org.apache.spark.sql.execution.SparkSqlAstBuilder.visitSetConfiguration(SparkSqlParser.scala:61)\n\tat org.apache.spark.sql.catalyst.parser.SqlBaseParser$SetConfigurationContext.accept(SqlBaseParser.java:8302)\n\tat org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitSingleStatement$3(AstBuilder.scala:653)\n\tat scala.Option.map(Option.scala:242)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitSingleStatement$1(AstBuilder.scala:653)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin(SparkParserUtils.scala:170)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin$(SparkParserUtils.scala:155)\n\tat org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:41)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.visitSingleStatement(AstBuilder.scala:654)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitCompoundOrSingleStatement$3(AstBuilder.scala:155)\n\tat scala.Option.getOrElse(Option.scala:201)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitCompoundOrSingleStatement$1(AstBuilder.scala:155)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin(SparkParserUtils.scala:170)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin$(SparkParserUtils.scala:155)\n\tat org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:41)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.visitCompoundOrSingleStatement(AstBuilder.scala:154)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.$anonfun$parsePlan$2(AbstractSqlParser.scala:96)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.$anonfun$withErrorHandling$1(AbstractSqlParser.scala:116)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin(SparkParserUtils.scala:170)\n\tat org.apache.spark.sql.catalyst.util.SparkParserUtils.withOrigin$(SparkParserUtils.scala:155)\n\tat org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:41)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.withErrorHandling(AbstractSqlParser.scala:115)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.$anonfun$parsePlan$1(AbstractSqlParser.scala:96)\n\tat org.apache.spark.sql.catalyst.parser.AbstractParser.parse(parsers.scala:81)\n\tat org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:54)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(AbstractSqlParser.scala:93)\n\tat org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:122)\n\tat org.apache.spark.sql.classic.SparkSession.$anonfun$sql$2(SparkSession.scala:451)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\n\tat org.apache.spark.sql.classic.SparkSession.$anonfun$sql$1(SparkSession.scala:450)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\n\tat org.apache.spark.sql.classic.SparkSession.sql(SparkSession.scala:449)\n\tat org.apache.spark.sql.classic.SparkSession.sql(SparkSession.scala:467)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:108)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n", "stacktrace": [{"class": null, "method": "deco", "file": "/home/airflow/.venv/lib/python3.13/site-packages/pyspark/errors/exceptions/captured.py", "line": "282"}, {"class": null, "method": "get_return_value", "file": "/home/airflow/.venv/lib/python3.13/site-packages/py4j/protocol.py", "line": "327"}]}}

"Error: \n[INVALID_SET_SYNTAX] Expected format is 'SET', 'SET key', or 'SET key=value'. If you want to include special characters in key, or include semicolon in value, please use backquotes, e.g., SET `key`=`value`. SQLSTATE: 42000\n== SQL (line 1, position 1) ==\nSET search_path = prod_db;\n^^^^^^^^^^^^^^^^^^^^^^^^^^\nSELECT * FROM customer;\n^^^^^^^^^^^^^^^^^^^^^^\n"

In [16]:
%%sql
select * from customer limit 1

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,1,Customer#000000001,j5JsirBM9PsCy0O1m,15,25-989-741-2988,711.56,BUILDING,y final requests wake slyly quickly special ac...

In [3]:
%%sql
SELECT
  n.n_name AS nation_c_name,
  s.quantity AS supplied_items_quantity,
  c.quantity AS purchased_items_quantity
FROM
  nation n
  LEFT JOIN (
    SELECT
      n.n_nationkey,
      SUM(l.l_quantity) AS quantity
    FROM
      lineitem l
      JOIN supplier s ON l.l_suppkey = s.s_suppkey
      JOIN nation n ON s.s_nationkey = n.n_nationkey
    GROUP BY
      n.n_nationkey
  ) s ON n.n_nationkey = s.n_nationkey
  LEFT JOIN (
    SELECT
      n.n_nationkey,
      SUM(l.l_quantity) AS quantity
    FROM
      lineitem l
      JOIN orders o ON l.l_orderkey = o.o_orderkey
      JOIN customer c ON o.o_custkey = c.c_custkey
      JOIN nation n ON c.c_nationkey = n.n_nationkey
    GROUP BY
      n.n_nationkey
  ) c ON n.n_nationkey = c.n_nationkey;

     nation_c_name supplied_items_quantity purchased_items_quantity
0            JAPAN               632809.00                594514.00
1           RUSSIA               719815.00                607446.00
2        ARGENTINA               583989.00                609330.00
3           JORDAN               435841.00                609850.00
4           FRANCE               534549.00                585564.00
5       MOZAMBIQUE               523591.00                613443.00
6           CANADA               569306.00                631774.00
7     SAUDI ARABIA               720977.00                569819.00
8         ETHIOPIA               506759.00                647056.00
9          ROMANIA               506500.00                628528.00
10         MOROCCO               624830.00                641135.00
11       INDONESIA               686980.00                659643.00
12            PERU               613397.00                568721.00
13           EGYPT               610765.00                627841.00
14           INDIA               719461.00                584063.00
15  UNITED KINGDOM               596263.00                606910.00
16         GERMANY               765812.00                619356.00
17            IRAN               609180.00                678349.00
18   UNITED STATES               551367.00                603133.00
19         VIETNAM               596045.00                607776.00
20            IRAQ               654510.00                625030.00
21           KENYA               545734.00                562545.00
22          BRAZIL               664553.00                618707.00
23         ALGERIA               558454.00                600846.00
24           CHINA               803315.00                633423.00

In [22]:
%%sql
SELECT
    o.o_orderkey,
    o.o_orderdate,
    COALESCE(l.l_orderkey, -1) AS lineitem_orderkey,
    l.l_shipdate
FROM
    orders o
    LEFT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
    AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY
    AND l.l_shipdate + INTERVAL '5' DAY
LIMIT
    10;

   o_orderkey o_orderdate  lineitem_orderkey  l_shipdate
0           1  1996-01-02                 -1        None
1           2  1996-12-01                 -1        None
2           3  1993-10-14                 -1        None
3           4  1995-10-11                 -1        None
4           5  1994-07-30                 -1        None
5           6  1992-02-21                 -1        None
6           7  1996-01-10                  7  1996-01-15
7          32  1995-07-16                 32  1995-07-21
8          33  1993-10-27                 33  1993-10-29
9          34  1998-07-21                 -1        None

In [4]:
%%sql --Write a query that shows the number of items returned for each region name

SELECT
    r.r_name as region_name,
    count(*) as count_of_region
FROM region as r
LEFT JOIN nation as n on r.r_regionkey = n.n_regionkey
LEFT JOIN supplier as s on s.s_nationkey= n.n_nationkey
LEFT JOIN lineitem as l on l.l_suppkey = s.s_suppkey
GROUP BY r.r_name

   region_name  count_of_region
0         ASIA           134374
1       EUROPE           122537
2      AMERICA           117023
3       AFRICA           107817
4  MIDDLE EAST           118821

In [29]:
%%sql
show tables in prod_db;

   namespace                  tableName  isTemporary
0    prod_db                     orders        False
1    prod_db               fct_lineitem        False
2    prod_db                   lineitem        False
3    prod_db                     nation        False
4    prod_db     order_lineitem_metrics        False
5    prod_db               dim_customer        False
6    prod_db                 stg_orders        False
7    prod_db               stg_customer        False
8    prod_db                 stg_nation        False
9    prod_db              wide_lineitem        False
10   prod_db                   partsupp        False
11   prod_db  customer_outreach_metrics        False
12   prod_db                   supplier        False
13   prod_db               stg_lineitem        False
14   prod_db                   customer        False
15   prod_db                       part        False
16   prod_db                 fct_orders        False
17   prod_db                     region        False
18   prod_db                 stg_region        False
19   prod_db                wide_orders        False

In [31]:
%%sql
select * from nation
limit 10

,n_nationkey,n_name,n_regionkey,n_comment
0,0,ALGERIA,0,furiously regular requests. platelets affix fu...
1,1,ARGENTINA,1,instructions wake quickly. final deposits hagg...
2,2,BRAZIL,1,asymptotes use fluffily quickly bold instructi...
3,3,CANADA,1,ss deposits wake across the pending foxes. pac...
4,4,EGYPT,4,"usly ironic, pending foxes. even, special inst..."
5,5,ETHIOPIA,0,regular requests sleep carefull
6,6,FRANCE,3,oggedly. regular packages solve across
7,7,GERMANY,3,ong the regular requests: blithely silent pint...
8,8,INDIA,2,uriously unusual deposits about the slyly fina...
9,9,INDONESIA,2,d deposits sleep quickly according to the dogg...

In [34]:
%%sql
select distinct r.r_name 
from region r
left join nation n
on r.r_regionkey = n.n_regionkey;

        r_name
0         ASIA
1       EUROPE
2      AMERICA
3       AFRICA
4  MIDDLE EAST

In [38]:
%%sql
SELECT * from orders limit 10;

,o_orderkey,o_custkey,o_orderstatus,o_totalprice,o_orderdate,o_orderpriority,o_clerk,o_shippriority,o_comment
0,1,3691,O,194029.55,1996-01-02,5-LOW,Clerk#000000951,0,ly express platelets. deposits acc
1,2,7801,O,60951.63,1996-12-01,1-URGENT,Clerk#000000880,0,ve the furiously fluffy dependencies. carefull...
2,3,12332,F,247296.05,1993-10-14,5-LOW,Clerk#000000955,0,after the asymptotes. instructions cajole aft...
3,4,13678,O,53829.87,1995-10-11,5-LOW,Clerk#000000124,0,st the furiously bold pinto beans. furiously p...
4,5,4450,F,139660.54,1994-07-30,5-LOW,Clerk#000000925,0,onic requests. carefully daring foxes among th...
5,6,5563,F,65843.52,1992-02-21,4-NOT SPECIFIED,Clerk#000000058,0,furiously ironic accounts haggle blithely care...
6,7,3914,O,231037.28,1996-01-10,2-HIGH,Clerk#000000470,0,", ironic packages wa"
7,32,13006,O,166802.63,1995-07-16,2-HIGH,Clerk#000000616,0,ly about the carefully express theodolites. ir...
8,33,6697,F,118518.56,1993-10-27,3-MEDIUM,Clerk#000000409,0,"careful, regular courts. unusual"
9,34,6101,O,75662.77,1998-07-21,3-MEDIUM,Clerk#000000223,0,osits according to the ideas are furiously fin...

In [4]:
%%sql --List the top 10 most selling parts (part name)

SELECT
    p.p_name as part_name,
    SUM(l.l_quantity) as total_sold
FROM part as p
INNER JOIN lineitem as l on p.p_partkey = l.l_partkey
GROUP BY p_partkey, p_name
ORDER BY total_sold DESC
LIMIT 10;

                               part_name total_sold
0         snow blanched blush linen blue    1484.00
1      moccasin brown puff thistle steel    1465.00
2    floral azure papaya moccasin indian    1427.00
3  blanched white ghost frosted metallic    1420.00
4         hot blue honeydew salmon slate    1413.00
5        lavender green brown linen dark    1412.00
6    frosted chocolate spring peach lawn    1398.00
7   hot blanched magenta yellow metallic    1389.00
8          orange white medium plum drab    1385.00
9              brown hot olive tan black    1382.00

In [20]:
%%sql -- Sellers (name) who have sold at least one of the top 10 selling parts
SELECT DISTINCT sup.s_name as supplier
FROM supplier as  sup
INNER JOIN partsupp as pupp on pupp.ps_suppkey = sup.s_suppkey
INNER JOIN
(
    SELECT 
        p.p_partkey,
        p.p_name as part_name,
        sum(l.l_quantity) as top_sells
    FROM lineitem as l
    INNER JOIN part as p on p.p_partkey = l.l_partkey
    GROUP BY p.p_partkey, p.p_name
    ORDER BY top_sells DESC
) as top_parts on top_parts.p_partkey = pupp.ps_partkey
LIMIT 10;

             supplier
0  Supplier#000000897
1  Supplier#000000487
2  Supplier#000000617
3  Supplier#000000900
4  Supplier#000000094
5  Supplier#000000538
6  Supplier#000000174
7  Supplier#000000274
8  Supplier#000000214
9  Supplier#000000240

In [18]:
%%sql

SELECT DISTINCT
    s.s_name AS seller_name
FROM lineitem AS l
INNER JOIN supplier AS s
    ON l.l_suppkey = s.s_suppkey
INNER JOIN (
    SELECT
        p.p_partkey
    FROM lineitem AS l
    INNER JOIN part AS p
        ON l.l_partkey = p.p_partkey
    GROUP BY
        p.p_partkey
) AS t
    ON l.l_partkey = t.p_partkey
LIMIT 10;

          seller_name
0  Supplier#000000897
1  Supplier#000000487
2  Supplier#000000617
3  Supplier#000000538
4  Supplier#000000094
5  Supplier#000000900
6  Supplier#000000174
7  Supplier#000000274
8  Supplier#000000240
9  Supplier#000000214

In [28]:
%%sql -- Number of items returned for each order price bucket. The definition of order price bucket is shown below.

SELECT count(*) as num_of_returns,
    CASE
        WHEN o.o_totalprice > 100000 THEN 'high'
        WHEN o.o_totalprice BETWEEN 25000 AND 100000 THEN 'medium'
    ELSE 'low'
END AS order_price_bucket
FROM lineitem as l
INNER JOIN orders as o on o.o_orderkey = l.l_orderkey
WHERE l.l_returnflag = 'R'
GROUP BY CASE
        WHEN o.o_totalprice > 100000 THEN 'high'
        WHEN o.o_totalprice BETWEEN 25000 AND 100000 THEN 'medium'
    ELSE 'low'
END
ORDER BY order_price_bucket ASC;

   num_of_returns order_price_bucket
0          121779               high
1            2745                low
2           23777             medium

In [49]:
%%sql -- Average time (in days) between receiptdate and shipdate for each nation (name)
SELECT n.n_name as nation,
       ROUND(AVG(date_diff(l.l_receiptdate, l.l_shipdate)), 2) as avg_delivery_days
FROM lineitem as l 
INNER JOIN orders o on o.o_orderkey = l.l_orderkey
INNER JOIN customer c on c.c_custkey = o.o_custkey
INNER JOIN nation n on n.n_nationkey = c.c_nationkey
WHERE l.l_shipdate is not null  and l.l_receiptdate is not null 
GROUP BY n.n_name
ORDER BY avg_delivery_days
LIMIT 10;

          nation  avg_delivery_days
0         BRAZIL              15.37
1        VIETNAM              15.39
2           IRAN              15.44
3          JAPAN              15.45
4       ETHIOPIA              15.45
5  UNITED STATES              15.46
6          EGYPT              15.46
7         CANADA              15.48
8         RUSSIA              15.48
9         JORDAN              15.49

In [5]:
%%sql

SELECT
    n.n_name AS nation_name,
    ROUND(AVG(DATEDIFF(l.l_receiptdate, l.l_shipdate)), 2) AS avg_delivery_days
FROM lineitem AS l
INNER JOIN orders AS o
    ON l.l_orderkey = o.o_orderkey
INNER JOIN customer AS c
    ON o.o_custkey = c.c_custkey
INNER JOIN nation AS n
    ON c.c_nationkey = n.n_nationkey
WHERE l.l_receiptdate IS NOT NULL
  AND l.l_shipdate IS NOT NULL
GROUP BY
    n.n_name
ORDER BY
    avg_delivery_days ASC
LIMIT 10;

     nation_name  avg_delivery_days
0         BRAZIL              15.37
1        VIETNAM              15.39
2           IRAN              15.44
3          JAPAN              15.45
4       ETHIOPIA              15.45
5  UNITED STATES              15.46
6          EGYPT              15.46
7         CANADA              15.48
8         RUSSIA              15.48
9         JORDAN              15.49

In [53]:
%%sql -- find the amount of money lost on discounts, Discounted price is in lineitem table called extendedprice, totalprice from orders table includes the discounted price, so difference between those columns give us total lost amount
with lineitem_agg as (
    SELECT
        l_orderkey,
        l_extendedprice,
        l_discount,
        
        SUM(l_extendedprice) as total_price_without_discount
    FROM lineitem
    GROUP BY l_orderkey, l_extendedprice
)
SELECT
    o.o_orderkey,
    l.l_extendedprice,
    o.o_totalprice,
    l.total_price_without_discount - o.o_totalprice as amount_lost_to_discount
FROM orders as o
JOIN lineitem_agg l on l.l_orderkey = o.o_orderkey
ORDER BY o.o_orderkey;

     o_orderkey l_extendedprice o_totalprice amount_lost_to_discount
0             1        10210.96    194029.55              -183818.59
1             1        31197.88    194029.55              -162831.67
2             1        46897.92    194029.55              -147131.63
3             1        58958.28    194029.55              -135071.27
4             1        31329.60    194029.55              -162699.95
..          ...             ...          ...                     ...
995         998         6713.28     87943.66               -81230.38
996         998        32705.10     87943.66               -55238.56
997         998         1148.24     87943.66               -86795.42
998         999        37447.33    181366.04              -143918.71
999         999        11652.60    181366.04              -169713.44

[1000 rows x 4 columns]

In [63]:
%%sql
with discounted_price as 
(
    SELECT l_orderkey,
        (1 - l_discount) * l_extendedprice as discounted_price
    FROM lineitem
)
SELECT o.o_totalprice,
       d.discounted_price
FROM orders as o
JOIN discounted_price as d on d.l_orderkey = o.o_orderkey
LIMIT 20;

   o_totalprice discounted_price
0     194029.55       23411.2032
1     194029.55       53652.0348
2     194029.55        9189.8640
3     194029.55       28390.0708
4     194029.55       28196.6400
5     194029.55       43615.0656
6      60951.63       58049.1800
7     247296.05       56277.1890
8     247296.05       79640.1900
9     247296.05       44613.9792
10    247296.05        3645.0414
11    247296.05       33016.9728
12    247296.05       26236.3140
13     53829.87       49842.4800
14    139660.54       25987.3950
15    139660.54       31564.3302
16    139660.54       76256.5000
17     65843.52       63925.7584
18    231037.28       12546.0720
19    231037.28       11919.2256

In [70]:
%%sql -- Sellers (name) who have sold at least one of the top 10 selling parts (use CTE)

with top_10 as (
    SELECT p.p_name,
           p.p_partkey,
           SUM(l.l_quantity) total_quantity
    FROM lineitem as l
    INNER JOIN part as p on p.p_partkey = l.l_partkey
    GROUP BY  p.p_partkey, p.p_name
    ORDER BY total_quantity DESC
    LIMIT 10
)
SELECT DISTINCT s.s_name as seller_name
FROM lineitem as l
INNER JOIN supplier as s on s.s_suppkey = l.l_suppkey
INNER JOIN top_10 as t on l.l_partkey = t.p_partkey
LIMIT 10;

          seller_name
0  Supplier#000000414
1  Supplier#000000782
2  Supplier#000000553
3  Supplier#000000296
4  Supplier#000000150
5  Supplier#000000585
6  Supplier#000000401
7  Supplier#000000115
8  Supplier#000000071
9  Supplier#000000053

In [71]:
%%sql 
SELECT
    o_custkey,
    o_orderdate,
    o_totalprice,
    SUM(o_totalprice) OVER(PARTITION BY o_custkey ORDER BY o_orderdate ) as running_sum
FROM orders
WHERE o_custkey = 4
ORDER BY o_orderdate
LIMIT 10;

   o_custkey o_orderdate o_totalprice running_sum
0          4  1992-06-09    261208.46   261208.46
1          4  1992-07-16    206615.30   467823.76
2          4  1992-10-11    222977.75   690801.51
3          4  1993-08-13     80130.69   770932.20
4          4  1993-11-13     66417.98   837350.18
5          4  1994-03-02    274992.65  1112342.83
6          4  1994-04-29    199636.40  1311979.23
7          4  1995-05-13    107127.51  1419106.74
8          4  1995-08-28    282207.37  1701314.11
9          4  1995-09-18    181789.20  1883103.31

In [74]:
%%sql 
select 261208.46 + 206615.30

  (261208.46 + 206615.30)
0               467823.76

In [83]:
%%sql --  Write a query to calculate the daily running average of the total price for every customer.

SELECT
    o_custkey,
    o_orderdate,
    o_totalprice,
    ROUND(AVG(o_totalprice) OVER(PARTITION BY o_custkey ORDER BY o_orderdate), 2) as running_sum
FROM orders
WHERE o_custkey = 4
ORDER BY o_orderdate
LIMIT 10;

   o_custkey o_orderdate o_totalprice running_sum
0          4  1992-06-09    261208.46   261208.46
1          4  1992-07-16    206615.30   233911.88
2          4  1992-10-11    222977.75   230267.17
3          4  1993-08-13     80130.69   192733.05
4          4  1993-11-13     66417.98   167470.04
5          4  1994-03-02    274992.65   185390.47
6          4  1994-04-29    199636.40   187425.60
7          4  1995-05-13    107127.51   177388.34
8          4  1995-08-28    282207.37   189034.90
9          4  1995-09-18    181789.20   188310.33

26/09/05 15:07:38 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 297318 ms exceeds timeout 120000 ms
26/09/05 15:07:38 WARN SparkContext: Killing executors is not supported by current scheduler.
26/09/05 15:07:38 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:81)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:669)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1296)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@c4fe02186768:39597
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/09/05 15:07:38 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@c4fe02186768:39597
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more

In [6]:
%%sql
SELECT * 
FROM (
    SELECT
        o_orderdate,
        o_totalprice,
        o_custkey,
        RANK() OVER(PARTITION BY o_orderdate ORDER BY o_totalprice DESC) as rnk 
    FROM orders
)
WHERE rnk <= 3
ORDER BY o_orderdate
LIMIT 5;

  o_orderdate o_totalprice  o_custkey  rnk
0  1992-01-01    358534.43      10942    1
1  1992-01-01    307146.32       5426    2
2  1992-01-01    306169.25      12973    3
3  1992-01-02    319926.05      12161    1
4  1992-01-02    302943.34      10526    2

In [7]:
%%sql
-- Let's look at an example showing the difference between RANK, DENSE_RANK and ROW_NUMBER
SELECT 
    order_date,
    order_id,
    total_price,
    ROW_NUMBER() OVER (PARTITION BY order_date ORDER BY total_price) AS row_number,
    RANK() OVER (PARTITION BY order_date ORDER BY total_price) AS rank,
    DENSE_RANK() OVER (PARTITION BY order_date ORDER BY total_price) AS dense_rank
FROM (
    SELECT 
        '2024-07-08' AS order_date, 'order_1' AS order_id, 100 AS total_price UNION ALL
    SELECT 
        '2024-07-08', 'order_2', 200 UNION ALL
    SELECT 
        '2024-07-08', 'order_3', 150 UNION ALL
    SELECT 
        '2024-07-08', 'order_4', 90 UNION ALL
    SELECT 
        '2024-07-08', 'order_5', 100 UNION ALL
    SELECT 
        '2024-07-08', 'order_6', 90 UNION ALL
    SELECT 
        '2024-07-08', 'order_7', 100 UNION ALL
    SELECT 
        '2024-07-10', 'order_8', 100 UNION ALL
    SELECT 
        '2024-07-10', 'order_9', 100 UNION ALL
    SELECT 
        '2024-07-10', 'order_10', 100 UNION ALL
    SELECT 
        '2024-07-11', 'order_11', 100
) AS orders
ORDER BY order_date, row_number;

    order_date  order_id  total_price  row_number  rank  dense_rank
0   2024-07-08   order_4           90           1     1           1
1   2024-07-08   order_6           90           2     1           1
2   2024-07-08   order_1          100           3     3           2
3   2024-07-08   order_5          100           4     3           2
4   2024-07-08   order_7          100           5     3           2
5   2024-07-08   order_3          150           6     6           3
6   2024-07-08   order_2          200           7     7           4
7   2024-07-10   order_8          100           1     1           1
8   2024-07-10   order_9          100           2     1           1
9   2024-07-10  order_10          100           3     1           1
10  2024-07-11  order_11          100           1     1           1

In [11]:
%%sql
SELECT
    order_month,
    o_custkey,
    total_price,
    ROUND(AVG(total_price) OVER(
        PARTITION BY o_custkey 
        ORDER BY order_month ROWS BETWEEN 1 PRECEDING 
        AND 1 FOLLOWING
        ), 2
    ) as three_mo_total_price_avg
FROM (
    SELECT
        date_format(o_orderdate, 'yyyy-MM') as order_month,
        o_custkey,
        SUM(o_totalprice) as total_price
    FROM orders
    GROUP BY 1, 2
    )
LIMIT 5;

  order_month  o_custkey total_price three_mo_total_price_avg
0     1992-04          1   367040.73                315144.14
1     1993-06          1   263247.54                221937.11
2     1994-12          1    35523.05                177975.27
3     1995-11          1   235155.22                117388.04
4     1996-05          1    81485.84                124770.33

In [21]:
%%sql
SELECT
    order_month,
    o_custkey,

    ROUND(
        AVG(total_price) OVER (
            PARTITION BY o_custkey
            ORDER BY order_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS three_mo_total_price_avg,

    ROUND(
        AVG(total_price) OVER (
            PARTITION BY o_custkey
            ORDER BY order_month
            RANGE BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS consecutive_three_mo_total_price_avg

FROM (
    SELECT
        CAST(DATE_TRUNC('MONTH', o_orderdate) AS DATE) AS order_month,
        o_custkey,
        SUM(o_totalprice) AS total_price
    FROM orders
    GROUP BY
        CAST(DATE_TRUNC('MONTH', o_orderdate) AS DATE),
        o_custkey
) t;

,order_month,o_custkey,three_mo_total_price_avg,consecutive_three_mo_total_price_avg
0,1992-04-01,1,367040.73,367040.73
1,1993-06-01,1,315144.14,263247.54
2,1994-12-01,1,221937.11,35523.05
3,1995-11-01,1,177975.27,235155.22
4,1996-05-01,1,117388.04,81485.84
...,...,...,...,...
995,1997-05-01,232,155717.12,169458.15
996,1997-06-01,232,139267.75,106899.66
997,1997-08-01,232,168160.22,228122.85
998,1998-04-01,232,118547.95,20621.34
999,1992-03-01,235,168993.79,168993.79

In [24]:

%%sql

WITH monthly_orders AS (
    SELECT
        CAST(date_format(o_orderdate, 'yyyy-MM-01') AS DATE) AS order_month,
        o_custkey,
        SUM(o_totalprice) AS total_price
    FROM orders
    GROUP BY
        CAST(date_format(o_orderdate, 'yyyy-MM-01') AS DATE),
        o_custkey
)

SELECT
    order_month,
    o_custkey,
    total_price,

    AVG(total_price) OVER (
        PARTITION BY o_custkey
        ORDER BY order_month
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS three_mo_total_price_avg,

    AVG(total_price) OVER (
        PARTITION BY o_custkey
        ORDER BY order_month
        RANGE BETWEEN INTERVAL 2 MONTHS PRECEDING AND CURRENT ROW
    ) AS consecutive_three_mo_total_price_avg

FROM monthly_orders

ORDER BY
    o_custkey,
    order_month

LIMIT 10;

,order_month,o_custkey,total_price,three_mo_total_price_avg,consecutive_three_mo_total_price_avg
0,1992-04-01,1,367040.73,367040.730000,367040.730000
1,1993-06-01,1,263247.54,315144.135000,263247.540000
2,1994-12-01,1,35523.05,221937.106667,35523.050000
3,1995-11-01,1,235155.22,177975.270000,235155.220000
4,1996-05-01,1,81485.84,117388.036667,81485.840000
5,1996-12-01,1,57669.94,124770.333333,57669.940000
6,1997-03-01,1,268835.44,135997.073333,268835.440000
7,1992-12-01,2,195693.26,195693.260000,195693.260000
8,1993-10-01,2,96852.91,146273.085000,96852.910000
9,1994-05-01,2,36433.77,109659.980000,36433.770000

In [29]:
%%sql
SELECT (81485.84 + 235155.22 + 57669.94	) / 3

  (((81485.84 + 235155.22) + 57669.94) / 3)
0                             124770.333333

In [36]:
%%sql
WITH daily_spending AS (
    SELECT
        CAST(o_orderdate AS DATE) AS order_date,
        o_custkey,
        SUM(o_totalprice) AS daily_spending
    FROM orders
    GROUP BY
        CAST(o_orderdate AS DATE),
        o_custkey
),

ranked_customers AS (
    SELECT
        order_date,
        o_custkey,
        daily_spending,
        RANK() OVER (
            PARTITION BY order_date
            ORDER BY daily_spending ASC
        ) AS spending_rank
    FROM daily_spending
)

SELECT
    order_date,
    o_custkey,
    daily_spending,
    spending_rank
FROM ranked_customers
WHERE spending_rank <= 3
ORDER BY
    order_date,
    spending_rank
LIMIT 20;

    order_date  o_custkey daily_spending  spending_rank
0   1992-01-01       9376       12781.38              1
1   1992-01-01       9103       25496.77              2
2   1992-01-01      14218       30944.67              3
3   1992-01-02       2746       16908.46              1
4   1992-01-02       4355       25445.96              2
5   1992-01-02       5311       26063.75              3
6   1992-01-03       6551       14538.00              1
7   1992-01-03      14972       23545.49              2
8   1992-01-03       6451       32810.77              3
9   1992-01-04      14423       15822.83              1
10  1992-01-04        679       27352.91              2
11  1992-01-04       3368       28626.13              3
12  1992-01-05       6908       17465.71              1
13  1992-01-05       4123       28187.72              2
14  1992-01-05      11455       31789.99              3
15  1992-01-06      12634        1649.73              1
16  1992-01-06      13108       20522.46              2
17  1992-01-06       4559       29183.35              3
18  1992-01-07      12860        2001.49              1
19  1992-01-07      11572       16689.25              2

In [31]:
%%sql
SELECT 
    CAST(o_orderdate as DATE) as order_date,
    o_custkey,
    sum(o_totalprice) as total
FROM orders
GROUP BY order_date, o_custkey

     order_date  o_custkey      total
0    1994-05-30      12167   71473.24
1    1995-08-16       7627   65277.88
2    1994-09-02        581  230053.01
3    1995-01-10       4858   64540.53
4    1997-01-20      13493  277139.27
..          ...        ...        ...
995  1996-02-17      10021   67155.54
996  1992-03-31       3292  139196.52
997  1994-09-19      12073  238149.91
998  1994-11-10      14264  142136.01
999  1992-01-24      11770  190399.10

[1000 rows x 3 columns]

In [40]:
%%sql
with daily_orders as (
SELECT o_orderdate,
       o_custkey,
       sum(o_totalprice) as totalprice
FROM orders
GROUP BY 1,2)
SELECT
    o_orderdate,
    o_custkey,
    ROUND(total_price - LAG(totalprice) OVER(PARTITION BY o_custkey ORDER BY o_orderdate), 2) as totalprice_diff
FROM daily_orders
LIMIT 20;

{"ts": "2026-09-05 17:53:39.716", "level": "ERROR", "logger": "SQLQueryContextLogger", "msg": "[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `total_price` cannot be resolved. Did you mean one of the following? [`totalprice`, `o_custkey`, `o_orderdate`]. SQLSTATE: 42703", "context": {"errorClass": "UNRESOLVED_COLUMN.WITH_SUGGESTION"}, "exception": {"class": "Py4JJavaError", "msg": "An error occurred while calling o38.sql.\n: org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `total_price` cannot be resolved. Did you mean one of the following? [`totalprice`, `o_custkey`, `o_orderdate`]. SQLSTATE: 42703; line 10 pos 10;\n'GlobalLimit 20\n+- 'LocalLimit 20\n   +- 'Project [o_orderdate#1009, o_custkey#1006L, 'ROUND(('total_price - lag(totalprice#1004, -1, null) windowspecdefinition(o_custkey#1006L, o_orderdate#1009 ASC NULLS FIRST, specifiedwindowframe(RowFrame, -1, -1))), 2) AS totalprice_diff#1003]\n      +- SubqueryAlias daily_orders\n         +- SubqueryAlias daily_orders\n            +- Aggregate [o_orderdate#1009, o_custkey#1006L], [o_orderdate#1009, o_custkey#1006L, sum(o_totalprice#1008) AS totalprice#1004]\n               +- SubqueryAlias local.prod_db.orders\n                  +- RelationV2[o_orderkey#1005L, o_custkey#1006L, o_orderstatus#1007, o_totalprice#1008, o_orderdate#1009, o_orderpriority#1010, o_clerk#1011, o_shippriority#1012, o_comment#1013] local.prod_db.orders local.prod_db.orders\n\n\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:401)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:169)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:404)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:402)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:252)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6(CheckAnalysis.scala:402)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6$adapted(CheckAnalysis.scala:402)\n\tat scala.collection.immutable.List.foreach(List.scala:334)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:402)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:284)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:252)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:284)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:255)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:299)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:244)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:231)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:299)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:192)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:192)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:76)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:111)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:71)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:330)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:330)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:110)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:278)\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:654)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:278)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\n\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:277)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:110)\n\tat scala.util.Try$.apply(Try.scala:217)\n\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1378)\n\tat org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1439)\n\tat org.apache.spark.util.LazyTry.get(LazyTry.scala:58)\n\tat org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:121)\n\tat org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:80)\n\tat org.apache.spark.sql.classic.Dataset$.$anonfun$ofRows$5(Dataset.scala:139)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\n\tat org.apache.spark.sql.classic.Dataset$.ofRows(Dataset.scala:136)\n\tat org.apache.spark.sql.classic.SparkSession.$anonfun$sql$1(SparkSession.scala:462)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\n\tat org.apache.spark.sql.classic.SparkSession.sql(SparkSession.scala:449)\n\tat org.apache.spark.sql.classic.SparkSession.sql(SparkSession.scala:467)\n\tat jdk.internal.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:108)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n\tSuppressed: org.apache.spark.util.Utils$OriginalTryStackTraceException: Full stacktrace of original doTryWithCallerStacktrace caller\n\t\tat org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:401)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:169)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7(CheckAnalysis.scala:404)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$7$adapted(CheckAnalysis.scala:402)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:252)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\t\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\t\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\t\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6(CheckAnalysis.scala:402)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$6$adapted(CheckAnalysis.scala:402)\n\t\tat scala.collection.immutable.List.foreach(List.scala:334)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:402)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:284)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:252)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\t\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:251)\n\t\tat scala.collection.immutable.Vector.foreach(Vector.scala:2125)\n\t\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:251)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:284)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:255)\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:299)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:244)\n\t\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:231)\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:299)\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:192)\n\t\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\t\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:192)\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:76)\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:111)\n\t\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:71)\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:330)\n\t\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:423)\n\t\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:330)\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:110)\n\t\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:148)\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:278)\n\t\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:654)\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:278)\n\t\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:804)\n\t\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:277)\n\t\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:110)\n\t\tat scala.util.Try$.apply(Try.scala:217)\n\t\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1378)\n\t\tat org.apache.spark.util.LazyTry.tryT$lzycompute(LazyTry.scala:46)\n\t\tat org.apache.spark.util.LazyTry.tryT(LazyTry.scala:46)\n\t\t... 21 more\n", "stacktrace": [{"class": null, "method": "deco", "file": "/home/airflow/.venv/lib/python3.13/site-packages/pyspark/errors/exceptions/captured.py", "line": "282"}, {"class": null, "method": "get_return_value", "file": "/home/airflow/.venv/lib/python3.13/site-packages/py4j/protocol.py", "line": "327"}]}}

"Error: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column, variable, or function parameter with name `total_price` cannot be resolved. Did you mean one of the following? [`totalprice`, `o_custkey`, `o_orderdate`]. SQLSTATE: 42703; line 10 pos 10;\n'GlobalLimit 20\n+- 'LocalLimit 20\n   +- 'Project [o_orderdate#1009, o_custkey#1006L, 'ROUND(('total_price - lag(totalprice#1004, -1, null) windowspecdefinition(o_custkey#1006L, o_orderdate#1009 ASC NULLS FIRST, specifiedwindowframe(RowFrame, -1, -1))), 2) AS totalprice_diff#1003]\n      +- SubqueryAlias daily_orders\n         +- SubqueryAlias daily_orders\n            +- Aggregate [o_orderdate#1009, o_custkey#1006L], [o_orderdate#1009, o_custkey#1006L, sum(o_totalprice#1008) AS totalprice#1004]\n               +- SubqueryAlias local.prod_db.orders\n                  +- RelationV2[o_orderkey#1005L, o_custkey#1006L, o_orderstatus#1007, o_totalprice#1008, o_orderdate#1009, o_orderpriority#1010, o_clerk#1011, o_shippriority#1012, o_comment#1013] local.prod_db.orders local.prod_db.orders\n"

In [42]:
%%sql

SELECT
    o_orderdate,
    o_custkey,
    o_totalprice as total_price,
    ROUND(
        total_price
        - LAG(total_price) OVER (
            PARTITION BY o_custkey
            ORDER BY o_orderdate
        ),
        2
    ) AS totalprice_diff
FROM orders
ORDER BY o_custkey, o_orderdate
LIMIT 10;

'Error: [UNSUPPORTED_FEATURE.LATERAL_COLUMN_ALIAS_IN_WINDOW] The feature is not supported: Referencing a lateral column alias `total_price` in window expression "LAG(lateralAliasReference(total_price)) OVER (PARTITION BY o_custkey ORDER BY o_orderdate ASC NULLS FIRST unspecifiedframe$())". SQLSTATE: 0A000'

In [44]:
%%sql
SELECT
    o_orderdate,
    o_custkey,
    o_totalprice,
    o_totalprice - LAG(o_totalprice) OVER (
    PARTITION BY o_custkey
    ORDER BY o_orderdate
    ) AS totalprice_diff
FROM orders
ORDER BY o_custkey, o_orderdate
LIMIT 10;

  o_orderdate  o_custkey o_totalprice totalprice_diff
0  1992-04-19          1     83779.26            None
1  1992-04-26          1    283261.47       199482.21
2  1993-06-22          1    263247.54       -20013.93
3  1994-12-24          1     35523.05      -227724.49
4  1995-11-01          1    235155.22       199632.17
5  1996-05-08          1     81485.84      -153669.38
6  1996-12-09          1     45744.09       -35741.75
7  1996-12-26          1     11925.85       -33818.24
8  1997-03-04          1    268835.44       256909.59
9  1992-12-07          2    195693.26            None